spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oss_transfer
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 2
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: org.hansk.tools.transfer.domain
oss:
  key: key
  secret: secret
  end_point: http://endpoint
  timeout: 1000
  buckets:
  - testbucket1
  - testbucket2
core_download: 2
max_download: 10

qiniu:
  access_key: qiniukey
  secret_key: qiniusecret